import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import { PrimeReactProvider } from "primereact/api";
import "../styles/theme/theme-light.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cais Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body className={inter.className}>{children}</body>
      </PrimeReactProvider>
    </html>
  );
}
