import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "../styles/globals.scss";
import { PrimeReactProvider } from "primereact/api";
import "../styles/theme/theme-light.scss";
import ReduxProvider from "@/components/Providers/ReduxProvider";
import { QueryClientProviderWrapper } from "@/components/Providers/QueryClientProvider";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Cais Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <PrimeReactProvider>
          <QueryClientProviderWrapper>
            <body className={roboto.className}>{children}</body>
          </QueryClientProviderWrapper>
        </PrimeReactProvider>
      </ReduxProvider>
    </html>
  );
}
